[package]
name = "rasta"
version = "0.1.0"
authors = ["Maxime Augier <max@xolus.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.4", features = ["full"]}
reqwest = { version = "0.11", features = ["rustls-tls", "json"] }
anyhow = "1.0"
tungstenite = { version = "0.13", features = ["rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
